
version: "3.9"

services:
  kafka:
    image: bitnami/kafka
    restart: unless-stopped
    mem_limit: ${KAFKA_MAX_MEM:-1024m}
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_MAX_MEM:-1024m} -Xms${KAFKA_MAX_MEM:-1024m}"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,CONTROLLER://:9093,PLAINTEXT_HOST://:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_NUM_PARTITIONS: 1
      KAFKA_CFG_LOG_RETENTION_HOURS: 24
      KAFKA_CFG_LOG_RETENTION_BYTES: 500000
      KAFKA_CFG_ACKS: "all"
      KAFKA_CFG_COMPRESSION_TYPE: "snappy"
      KAFKA_CFG_RETRIES: 0
      KAFKA_CFG_MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: 1
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka:/bitnami/kafka
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


  kowl:
    image: rsmnarts/kowl
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      KAFKA_BROKERS: kafka:29092

  mongo_setup:
    image: mongo
    restart: on-failure
    volumes:
      - ./scripts/mongo_setup.sh:/scripts/setup.sh
    entrypoint: [ "/bin/bash", "/scripts/setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    image: mongo
    ports:
      - 27017:27017
    restart: on-failure
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo1:/data/db

  mongo2:
    image: mongo
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo2:/data/db

  mongo3:
    image: mongo
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo3:/data/db

  mongo4:
    image: mongo
    ports:
      - 27020:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo4:/data/db
  mongo5:
    image: mongo
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo5:/data/db
  mongo6:
    image: mongo
    ports:
      - 27021:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--journal", "--dbpath", "/data/db" ]
    volumes:
      - mongo5:/data/db
volumes:
  kafka:
  mongo1:
  mongo2:
  mongo3:
